//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public GiaoVien()
        {
            this.LopHocs = new HashSet<LopHoc>();
            this.PhanCongGiangDays = new HashSet<PhanCongGiangDay>();
            this.ThoiKhoaBieux = new HashSet<ThoiKhoaBieu>();
        }
    
        public int GiaoVienID { get; set; }
        public int NguoiDungID { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TrangThaiGiangDay { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> MonHocID { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
    }
}
