//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocBu
    {
        public int HocBuID { get; set; }
        public int NgayNghiID { get; set; }
        public int NgayHocBuID { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NgayHoc NgayHoc { get; set; }
        public virtual NgayHoc NgayHoc1 { get; set; }
    }
}
