//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocKy
    {
        public HocKy()
        {
            this.Diems = new HashSet<Diem>();
            this.KetQuaHocTaps = new HashSet<KetQuaHocTap>();
            this.PhanCongGiangDays = new HashSet<PhanCongGiangDay>();
            this.ThoiKhoaBieux = new HashSet<ThoiKhoaBieu>();
        }
    
        public int HocKyID { get; set; }
        public string TenHocKy { get; set; }
        public int NamHocID { get; set; }
        public int SoTuanThucHoc { get; set; }
    
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual ICollection<KetQuaHocTap> KetQuaHocTaps { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
    }
}
