//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        public LopHoc()
        {
            this.HocSinh = new HashSet<HocSinh>();
            this.PhanCongGiangDay = new HashSet<PhanCongGiangDay>();
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int LopHocID { get; set; }
        public string TenLop { get; set; }
        public Nullable<int> SiSO { get; set; }
        public Nullable<int> GiaoVienChuNhiem { get; set; }
        public Nullable<int> NienKhoa { get; set; }
        public int KhoiLopID { get; set; }
        public string CaHoc { get; set; }
        public Nullable<int> PhongHocID { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual ICollection<HocSinh> HocSinh { get; set; }
        public virtual KhoiLop KhoiLop { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDay { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
    }
}
