//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTruongHocEntities : DbContext
    {
        public QuanLyTruongHocEntities()
            : base("name=QuanLyTruongHocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BoMon> BoMons { get; set; }
        public DbSet<Diem> Diems { get; set; }
        public DbSet<GiaoVien> GiaoViens { get; set; }
        public DbSet<HocBu> HocBus { get; set; }
        public DbSet<HocKy> HocKies { get; set; }
        public DbSet<HocSinh> HocSinhs { get; set; }
        public DbSet<HocSinh_PhuHuynh> HocSinh_PhuHuynh { get; set; }
        public DbSet<KetQuaHocTap> KetQuaHocTaps { get; set; }
        public DbSet<KhoiLop> KhoiLops { get; set; }
        public DbSet<LopHoc> LopHocs { get; set; }
        public DbSet<MonHoc> MonHocs { get; set; }
        public DbSet<MonHocKhoi> MonHocKhois { get; set; }
        public DbSet<NamHoc> NamHocs { get; set; }
        public DbSet<NgayHoc> NgayHocs { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public DbSet<PhongHoc> PhongHocs { get; set; }
        public DbSet<PhuHuynh> PhuHuynhs { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
        public DbSet<ThongBao> ThongBaos { get; set; }
        public DbSet<ThongBaoDaDoc> ThongBaoDaDocs { get; set; }
    }
}
