//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHocKhoi
    {
        public int MonHocKhoiID { get; set; }
        public int MonHocID { get; set; }
        public int KhoiLopID { get; set; }
        public int SoTietNam { get; set; }
    
        public virtual KhoiLop KhoiLop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
