//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamHoc
    {
        public NamHoc()
        {
            this.Diems = new HashSet<Diem>();
            this.HocKies = new HashSet<HocKy>();
            this.KetQuaHocTaps = new HashSet<KetQuaHocTap>();
            this.LopHocs = new HashSet<LopHoc>();
            this.ThoiKhoaBieux = new HashSet<ThoiKhoaBieu>();
        }
    
        public int NamHocID { get; set; }
        public string TenNamHoc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual ICollection<HocKy> HocKies { get; set; }
        public virtual ICollection<KetQuaHocTap> KetQuaHocTaps { get; set; }
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
    }
}
