//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgayHoc
    {
        public NgayHoc()
        {
            this.HocBus = new HashSet<HocBu>();
            this.HocBus1 = new HashSet<HocBu>();
        }
    
        public int NgayHocID { get; set; }
        public System.DateTime Ngay { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<HocBu> HocBus { get; set; }
        public virtual ICollection<HocBu> HocBus1 { get; set; }
    }
}
