//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demomvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.GiaoViens = new HashSet<GiaoVien>();
            this.HocSinhs = new HashSet<HocSinh>();
            this.ThongBaoDaDocs = new HashSet<ThongBaoDaDoc>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public int NguoiDungID { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string VaiTro { get; set; }
        public string TrangThaiTK { get; set; }
        public string AnhDaiDien { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> ResetTokenExpiry { get; set; }
    
        public virtual ICollection<GiaoVien> GiaoViens { get; set; }
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
        public virtual ICollection<ThongBaoDaDoc> ThongBaoDaDocs { get; set; }
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
